### ISSUE TITLE
Docker 部署 ChatGPT-Next-Web 问题

### ISSUE THREAD

**Issue by dahai2626** [cliouo/FreeGPT35-Vercel#11]
首先感谢大神的付出！
服务器Docker 部署之后(已再环境中设置BASE_URL:http://[ip]:3040)打开ChatGPT-Next-Web 的页面需要手动设置 【自定义接口】- 【接口地址】 改成FreeGPT35 部署后的地址http://[ip]:3040  不然用不了，怎么解可以在打开ChatGPT-Next-Web 不需要重新配置自定义接口地址？

**Comment by cliouo** [comment]
首先不用感谢我，Docker部署不是我的工作，是上游的工作，Docker使用你可以关注下上游的项目。
不过我可以帮你参考一下
```
CODE: "HelloGPT" # 如果你想要设置页面的访问密码，请修改这里
```
我看到上游的docker compose文件内有默认设置的访问密码，我不知道你是否有输入。
不然的话，文件内确实包含了
```
BASE_URL: "http://freegpt35:3040"
```
不应该会出现默认不能使用的情况

**Comment by dahai2626** [comment]
没有配置code(这个是用来加密访问用的)，环境中配置了BASE。web访问f12查看到请求的链接是：http://[freegpt35 ip]:3040/api/openai/v1/chat/completions 内容自动多了openai/v1 注chatgpt-next-web版本为V2.11.3
