### ISSUE TITLE
Branch "vercel-pro" not found in the connected Git repository.

### ISSUE THREAD

**Issue by cfurcn** [cliouo/FreeGPT35-Vercel#13]
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/151720837/e48dae12-145a-4630-8967-90de79ebfeb2)

**Comment by cliouo** [comment]
fork本仓库，并且fork的时候，取消勾选那个只fork main

**Comment by cfurcn** [comment]
> fork本仓库，并且fork的时候，取消勾选那个只fork main

大佬，我还是遇到了问题。
我fork了仓库，然后使用了fork之后的地址去创建，创建之后任然无法修改 vercel-pro 保存。
能够回复，万分感谢！

**Comment by cliouo** [comment]
fork的时候取消勾选那个只fork main应该就会有这个分支呀

**Comment by cfurcn** [comment]
> fork的时候取消勾选那个只fork main应该就会有这个分支呀

![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/151720837/95fe58ec-6f71-4bf4-80ae-6f24a99d9ffd)
Create fork

![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/151720837/5b4e5262-ea03-457d-bf0e-d0a2b10eb314)
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/151720837/862c8be2-87db-4878-bba7-006cd2b61bf4)
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/151720837/26e88bb9-930b-4403-b1ad-85d4b7629147)

我也不知道啥情况了，不知道有没有哪里做的不对。

**Comment by cliouo** [comment]
嗷才发现哪里不对，你怎么是导入的仓库url，一般都是自己fork完以后，vercel首页点New Project然后能点击github认证，认证完可以选择导入你github账号里的哪个仓库，对着你frok的仓库点 import，一般是这样导入vercel的

**Comment by cliouo** [comment]
反正你输链接的地方前面有个 分支 的图标，代表这个链接肯定代表分支的，然后默认main，所以只能部署main，建议还是上一条回复的方式，去自己vercel首页New Project导入自己的仓库
