### ISSUE TITLE
这个问题怎么解决？

### ISSUE THREAD

**Issue by buwanyuanshen** [cliouo/FreeGPT35-Vercel#14]
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/144007759/6f6ba153-dd7b-4233-91dd-7f2389b134c8)
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/144007759/6a1f9a58-9981-47ad-9baa-4b7f44b442c3)
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/144007759/e528692c-2515-40d2-a22c-e0aeb9a16422)

**Comment by buwanyuanshen** [comment]
奇怪的事来了，部署完后把github的项目删了后就正常了。

**Comment by buwanyuanshen** [comment]
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/144007759/6e4e958f-b405-49f6-b9a0-7ed9772b4b7a)
说明里的环境变量是不是不对呢，设置成这个就行了

**Comment by cliouo** [comment]
我的我的，昨天脑子也乱了，我改过环境变量名，结果我也没分清哈哈
