### ISSUE TITLE
无服务器函数崩溃

### ISSUE THREAD

**Issue by DSLZL** [cliouo/FreeGPT35-Vercel#15]
<img width="572" alt="屏幕截图 2024-04-11 171029" src="https://github.com/cliouo/FreeGPT35-Vercel/assets/92631890/bbf61452-4b6c-49a5-8409-92c4b5467250">

**Comment by DSLZL** [comment]
api/cron

**Comment by cliouo** [comment]
大概率你数据库没配置好，因为这函数很小，只有连接不上数据库才会报错了

**Comment by cliouo** [comment]
配置好数据库后要点Redeploy重新构建一次，环境变量才会生效

**Comment by DSLZL** [comment]
> 配置好数据库后要点Redeploy重新构建一次，环境变量才会生效

我看了你的教程和那个issue，到底是api还是Redis？

**Comment by DSLZL** [comment]
> > 配置好数据库后要点Redeploy重新构建一次，环境变量才会生效
> 
> 我看了你的教程和那个issue，到底是api还是Redis？

我两个都试了也是这样

**Comment by cliouo** [comment]
目前的是最新的，正确的，肯定没问题呀，我自己就用的这个
![c21db0b50e26b776547224150840ab29.png](https://ice.frostsky.com/2024/04/11/c21db0b50e26b776547224150840ab29.png)

**Comment by DSLZL** [comment]
> 目前的是最新的，正确的，肯定没问题呀，我自己就用的这个
> ![c21db0b50e26b776547224150840ab29.png](https://ice.frostsky.com/2024/04/11/c21db0b50e26b776547224150840ab29.png)

ok，我去试试

**Comment by DSLZL** [comment]
All done,thanks you.
