### ISSUE TITLE
在沉浸式翻译中最佳参数设置

### ISSUE THREAD

**Issue by Ryan2009** [cliouo/FreeGPT35-Vercel#17]
使用的是vercel 和 upstash . 沉浸式翻译中这几个参数怎么填，能让翻译的速度最快？
![1712853647803](https://github.com/cliouo/FreeGPT35-Vercel/assets/13790961/922328ab-c65a-4ee9-9930-45b0a7666a15)

**Comment by cliouo** [comment]
这个我没有测试过，我是500-700，并发30左右，段落没动
