### ISSUE TITLE
方法二 图片有误

### ISSUE THREAD

**Issue by stvlynn** [cliouo/FreeGPT35-Vercel#20]
第6部下面图片的变量名称应该是UPSTASH_REDIS_REST_URL和UPSTASH_REDIS_REST_TOKEN

**Comment by cliouo** [comment]
其实我改了呀，不过是同名文件有缓存还是显示旧版，话说我都改了四五天了这个缓存还没完全刷新吗

**Comment by cliouo** [comment]
算了换个文件名刷新一下.

**Comment by cliouo** [comment]
嗷是我改错了，那没事了
