### ISSUE TITLE
关于我提供的试用接口的说明

### ISSUE THREAD

**Issue by cliouo** [cliouo/FreeGPT35-Vercel#21]
试用api为单账号部署，额度不高，目前禁止接入oneapi等分发平台
- API试用: 
https://testgpt.iqaq.me/v1/chat/completions
- chatgpt-next-web试用: 
https://chat.iqaq.me

以上均使用Vercel Pro和Upstash账号部署，受限单账号Upstash数据库每日`10k`调用限制，以上试用接口每天大概能用`8k`次
其中:
- `testgpt.iqaq.me`我是有**消息日志记录**的 ，防止号商白嫖，*使用量太高时我会看一下是不是号商*
*(就是能看到你发了啥，为了保留查询，一般不会看，介意的话自己部署)*
- `chat.iqaq.me`没有消息日志记录

今日发现试用API的 `16token/4min`，在下午有一个b `2分钟2.5k请求`下出现429频繁，所以提升到`24token/3min`
虽然不算违规，但还是建议用量大的自己部署一下

**Comment by cliouo** [comment]
43.132.*.* 这哥们24小时不停翻译小说用量太大了, 1个人顶20个人 ban了，要用自己部署，

**Comment by cliouo** [comment]
暂时寄咯，等上游解决

**Comment by cliouo** [comment]
token现在一次就失效，测了很多办法都失效，只能每次请求拿新的了，并发基本没可能了1qps玩吧

**Comment by navhub007** [comment]
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/136465762/85126489-7b4c-498a-aa23-3e1cb768a93d)
在Nextchat中输入所生成的地址出现：
{
  "error": true,
  "message": "Failed to fetch"
}

我该怎么办？我搞了几天了

**Comment by cliouo** [comment]
> ![image](https://private-user-images.githubusercontent.com/136465762/329797377-85126489-7b4c-498a-aa23-3e1cb768a93d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzI1MzAsIm5iZiI6MTcxNTUzMjIzMCwicGF0aCI6Ii8xMzY0NjU3NjIvMzI5Nzk3Mzc3LTg1MTI2NDg5LTdiNGMtNDk4YS1hYTIzLTNlMWNiNzY4YTkzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxNjQzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzA3YzAyZGM0ZjkzZWNhMTA3Mzk1NGI3ZmM5YzMyZjU1NDQwNWQ2YTc4YjQ3ZTkzNTVhYzIzODJjZjFlOGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1BAj1gX3qwOtVV-dcExTt2Scj5FXV4i5Hl_CkMlBlKY) 在Nextchat中输入所生成的地址出现： { "error": true, "message": "Failed to fetch" }
> 
> 我该怎么办？我搞了几天了

很明显你这域名不对，你这链接复制到无痕能打开吗，无痕打开要登录就不对，自己琢磨一下，要么就绑自己域名

**Comment by navhub007** [comment]
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/136465762/6e1f0c9d-e5ea-4b57-9d0e-4ba8b4f3c765)
我绑定了域名，无痕打开如上图，不需要登录，也用不了

**Comment by navhub007** [comment]
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/136465762/640fa2c1-910e-423a-a866-00ced0dde2f3)
我不知道我错过了什么，无痕能打开，无痕打开不需要登录，绑定了域名的

**Comment by cliouo** [comment]
> ![image](https://private-user-images.githubusercontent.com/136465762/330550941-640fa2c1-910e-423a-a866-00ced0dde2f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDkwMjcsIm5iZiI6MTcxNTc0ODcyNywicGF0aCI6Ii8xMzY0NjU3NjIvMzMwNTUwOTQxLTY0MGZhMmMxLTkxMGUtNDIzYS1hODY2LTAwY2VkMGRkZTJmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwNDUyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmY0ODQzNDg4OGZkNDRlMWJmZDQ0OGJjY2RhMThjNmUxY2I5OWVmNTViNTljYWIxZTU3N2E0OGQ1Nzc0NWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HBqTRjT5GUmCqpCCRCGGNbBBuUuX9BbHwPwZS4Qp3tg) 我不知道我错过了什么，无痕能打开，无痕打开不需要登录，绑定了域名的

因为不是这样用的啊，本来就不能直接浏览器访问/v1/chat/completions
