### ISSUE TITLE
{"error":"获取会话 ID 和令牌失败"}

### ISSUE THREAD

**Issue by sdlkhfksl** [cliouo/FreeGPT35-Vercel#22]
{
  "error": true,
  "message": "empty response from server"
}

**Comment by cliouo** [comment]
数据库配好了没，自己看下log日志，有问题建议可以贴一下日志报错
目前这个
```
{"error":"获取会话 ID 和令牌失败"}
```
只有所有令牌一个都拿不到的情况下才会返回，或者数据库没配好
下面这个我就还没见过
```
{
"error": true, 
"message": "empty response from server" 
}
```
因为代码很简单，部署环境又很唯一，因此目前还没遇到过什么问题，参照下图看下日志
![image](https://github.com/cliouo/FreeGPT35-Vercel/assets/71540889/7d9a7bed-e04a-4d96-b2c0-abff1a8c1f24)

**Comment by sdlkhfksl** [comment]
![屏幕截图 2024-04-19 101134](https://github.com/cliouo/FreeGPT35-Vercel/assets/97817853/e4ef186d-24c4-45c1-8478-f2a123abe158)
大佬，这个怎么处理啊

**Comment by sdlkhfksl** [comment]
![屏幕截图 2024-04-19 103734](https://github.com/cliouo/FreeGPT35-Vercel/assets/97817853/1052f871-837d-45e1-90fd-f47dab0df826)
大佬帮我看看，到底哪里出错了，谢谢

**Comment by cliouo** [comment]
只能是数据库问题，填完重新部署了吗

**Comment by sdlkhfksl** [comment]
> 只能是数据库问题，填完重新部署了吗

是数据库写的格式不对吗？重新部署还是一样的错误

**Comment by sdlkhfksl** [comment]
url 格式写错了
