### ISSUE TITLE
关于分支有个问题想问一下

### ISSUE THREAD

**Issue by mundane799699** [cliouo/FreeGPT35-Vercel#23]
vercel部署的时候是部署main分支吗？
那为什么需要取消勾选Copy the main branch only呢？
这里不太明白，希望作者解答一下。

别的都很棒棒，给作者点赞！

**Comment by cliouo** [comment]
因为main分支是给免费计划用的, 还有一个vercel-pro分支是给vercel pro用的, 勾不勾这个本身无所谓, 但是我写教程有人要用pro的,到时候他们再遇到没fork pro的分支而部署不了咋办
