### ISSUE TITLE
/v1/chat/completions访问出现错误

### ISSUE THREAD

**Issue by Love-AronaPlana** [cliouo/FreeGPT35-Vercel#24]
![Clip_2024-04-20_11-52-19](https://github.com/cliouo/FreeGPT35-Vercel/assets/51117375/e847f66a-38d5-4bee-97db-3c1671677627)
![Clip_2024-04-20_11-52-56](https://github.com/cliouo/FreeGPT35-Vercel/assets/51117375/da170462-20fe-41b2-8422-b9586fbadf19)
直接输入域名能正常访问，但输入/v1/chat/completions无法正常访问，把域名放到chatbox里面也报错

**Comment by Love-AronaPlana** [comment]
![Clip_2024-04-20_11-55-29](https://github.com/cliouo/FreeGPT35-Vercel/assets/51117375/97c6201a-024c-4415-8d70-414916b03fa7)

**Comment by cliouo** [comment]
首先浏览器直接访问/v1/chat/completions是肯定不能访问的，其次目前暂时寄咯，等上游解决吧
