### ISSUE TITLE
是已经失效了吗？怎么回事求教。

### ISSUE THREAD

**Issue by tlerbao** [cliouo/FreeGPT35-Vercel#25]
接口返回下面的信息

<img width="1053" alt="CleanShot 2024-04-20 at 17 04 59@2x" src="https://github.com/cliouo/FreeGPT35-Vercel/assets/20442232/5d9011ca-084d-4d42-aa19-92e256c5381d">

**Comment by buwanyuanshen** [comment]
好像是，现在都是空回复了

**Comment by buwanyuanshen** [comment]
薅了openai一个星期多了，不亏奥

**Comment by cliouo** [comment]
暂时寄咯，等上游解决吧

**Comment by cliouo** [comment]
> 接口返回下面的信息
> 
> <img alt="CleanShot 2024-04-20 at 17 04 59@2x" width="1053" src="https://private-user-images.githubusercontent.com/20442232/324167170-5d9011ca-084d-4d42-aa19-92e256c5381d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NTk2NjMsIm5iZiI6MTcxMzY1OTM2MywicGF0aCI6Ii8yMDQ0MjIzMi8zMjQxNjcxNzAtNWQ5MDExY2EtMDg0ZC00ZDQyLWFhMTktOTJlMjU2YzUzODFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAwMjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NTUxMzZiZGE2N2VjODI4ZjA4NGZiNmZkYjZiYWJkYWQ4NmYwOWRkYzJhYjVjZGRhZGEwOTg5MjM1ZTgyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BWJdUMRlm09XLynIyB6KJsWk4A0XVl5f4uW8Ds-ji3Q">

应该回复了，拉一下最新的代码试试呢，部署完记得访问/api/cron更新一下token

**Comment by cliouo** [comment]
> 好像是，现在都是空回复了

应该恢复了，拉一下最新的代码试试呢，部署完记得访问/api/cron更新一下token

**Comment by cliouo** [comment]
token现在一次就失效，测了很多办法都失效，只能每次请求拿新的了，并发基本没可能了1qps玩吧

**Comment by ghost** [comment]
> token现在一次就失效，测了很多办法都失效，只能每次请求拿新的了，并发基本没可能了1qps玩吧

没用多久就失效了吗，哎
