### ISSUE TITLE
用那个一键平台搭建后返回的结果好像要本地地址

### ISSUE THREAD

**Issue by OSNewbie** [cliouo/FreeGPT35-Vercel#4]
{"status":false,"error":{"message":"未找到请求的端点。请确保使用 \"http://localhost:3040/v1\" 作为基本 URL。","类型":"invalid_request_error"}}

**Comment by yet8main** [comment]
提示仅仅是这么提示的，忽略就好。
部署完就用vercel给你的地址，类似于 https://project-wzyazkwxm.vercel.app 这样。

**Comment by xingmolu** [comment]
部署完怎么访问呢，我访问都是返回这个错误 {"status":false,"error":{"message":"未找到请求的端点。请确保使用 "[http://localhost:3040/v1\](http://localhost:3040/v1%5C)" 作为基本 URL。","类型":"invalid_request_error"}}

**Comment by yet8main** [comment]
> 部署完怎么访问呢，我访问都是返回这个错误 {"status":false,"error":{"message":"未找到请求的端点。请确保使用 "[http://localhost:3040/v1](http://localhost:3040/v1%5C)" 作为基本 URL。","类型":"invalid_request_error"}}

出现这个就是成功了，`post /v1/chat/completions` 端点就可以了

---
如果不熟悉代码，可以直接使用 https://app.nextchat.dev/
- 点击左下角设置图标，找到图中所示设置
![图片](https://github.com/cliouo/FreeGPT35-Vercel/assets/166087712/8ee04641-af59-4325-b6d9-b404e22dab46)
- **接口地址**填你的网址，例如作者的 https://freegpt35.iqaq.me
- **API KEY**填你在vercel项目的环境变量里设置的密钥值，**如果你不知道这是什么，也没设置过，请直接放空就可以**
- 返回主界面就可以正常对话了

**Comment by xingmolu** [comment]
ok 了，原来是 post 请求。。一直用的 get。。
