### ISSUE TITLE
自定义域名后报错Unauthorized

### ISSUE THREAD

**Issue by dachuan** [cliouo/FreeGPT35-Vercel#7]
只有使用openAI的python库发起请求是正常的
用python requests，或是在chatGPT Next中，都是报错：`Unauthorized `
另外，使用`https://freegpt35.iqaq.me/`都OK，需要在vercel中进行什么额外设置？

**Comment by cliouo** [comment]
我啥也没设置呀，报500和504我可以理解，确实有问题，401我就不理解了，下午确实有一小时要求填默认key，现在应该不会遇到这个吧，还是你代码刚好是下午要求默认key的那一版?

**Comment by dachuan** [comment]
2h之前的版本

**Comment by Barry-Aerbeita-zhou** [comment]
> 只有使用openAI的python库发起请求是正常的 用python requests，或是在chatGPT Next中，都是报错：`Unauthorized ` 另外，使用`https://freegpt35.iqaq.me/`都OK，需要在vercel中进行什么额外设置？

大概率是密码错了，重新设置环境变量并部署
